services:
  backend:
    build:
      context: ./TeslaRenting/
    ports:
      - "5106:5106"
    environment:
      - ASPNETCORE_URLS=http://+:5106
    networks:
      - omnicatalogue-net

  frontend:
    build:
      context: ./UI/tesla-renting-ui/
    ports:
      - "5173:80"
    networks:
      - omnicatalogue-net
    environment:
      - VITE_BACKEND_URL=http://localhost:5106

networks:
  omnicatalogue-net:
    driver: bridge
