// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeslaRenting.Data.Entity;

#nullable disable

namespace TeslaRenting.Migrations
{
    [DbContext(typeof(TeslaRentingDbContext))]
    [Migration("20231025141159_yomahart")]
    partial class yomahart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TeslaRenting.Data.Entity.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Krakow",
                            Country = "Poland",
                            PostalCode = "31-154",
                            Street = "Pawia"
                        });
                });

            modelBuilder.Entity("TeslaRenting.Data.Entity.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeslaCarId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeslaCarId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("TeslaRenting.Data.Entity.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "User"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Employee"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("TeslaRenting.Data.Entity.TeslaCar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailableAt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TeslaCars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvailableAt = "PalmaAirport",
                            DailyRate = 100.00m,
                            Description = "Five-door compact sedan (segment C) equipped with a fully electric drive (can travel approximately 350 km on a single charge), produced since 2017. The model year is 2017, with a 320HP 222kW P60 engine.",
                            Name = "Model 3"
                        },
                        new
                        {
                            Id = 2,
                            AvailableAt = "PalmaAirport",
                            DailyRate = 1200.00m,
                            Description = "Luxury model in the E segment, powered by an electric motor with 1020HP, 750kW of power, capable of traveling approximately 637km on a single charge. Model year 2021. It has 5 doors.",
                            Name = "Model S"
                        },
                        new
                        {
                            Id = 3,
                            AvailableAt = "PalmaAirport",
                            DailyRate = 240.00m,
                            Description = "Built on the Model S platform, the Model X was designed to combine the best features of an SUV and a minivan while maintaining sporty performance. The main feature of the Model X is the upward-lifting rear pair of doors - Falcon Wing Doors. The car is from the 2017 model year, with a 503HP 370kW P100D engine.",
                            Name = "Model X"
                        },
                        new
                        {
                            Id = 4,
                            AvailableAt = "PalmaAirport",
                            DailyRate = 190.00m,
                            Description = "It features a range of up to 507 kilometers on a single charge and all-wheel drive (AWD) with a dual-motor setup. The vehicle accelerates from 0 to 100 km/h in 5 seconds, and its maximum speed is 217 km/h. It's a comfortable 5-door car with a 450HP engine.",
                            Name = "Model Y"
                        },
                        new
                        {
                            Id = 5,
                            AvailableAt = "PalmaCityCenter",
                            DailyRate = 100.00m,
                            Description = "Five-door compact sedan (segment C) equipped with a fully electric drive (can travel approximately 350 km on a single charge), produced since 2017. The model year is 2017, with a 320HP 222kW P60 engine.",
                            Name = "Model 3"
                        },
                        new
                        {
                            Id = 6,
                            AvailableAt = "PalmaCityCenter",
                            DailyRate = 1200.00m,
                            Description = "Luxury model in the E segment, powered by an electric motor with 1020HP, 750kW of power, capable of traveling approximately 637km on a single charge. Model year 2021. It has 5 doors.",
                            Name = "Model S"
                        },
                        new
                        {
                            Id = 7,
                            AvailableAt = "PalmaCityCenter",
                            DailyRate = 240.00m,
                            Description = "Built on the Model S platform, the Model X was designed to combine the best features of an SUV and a minivan while maintaining sporty performance. The main feature of the Model X is the upward-lifting rear pair of doors - Falcon Wing Doors. The car is from the 2017 model year, with a 503HP 370kW P100D engine.",
                            Name = "Model X"
                        },
                        new
                        {
                            Id = 8,
                            AvailableAt = "PalmaCityCenter",
                            DailyRate = 190.00m,
                            Description = "It features a range of up to 507 kilometers on a single charge and all-wheel drive (AWD) with a dual-motor setup. The vehicle accelerates from 0 to 100 km/h in 5 seconds, and its maximum speed is 217 km/h. It's a comfortable 5-door car with a 450HP engine.",
                            Name = "Model Y"
                        },
                        new
                        {
                            Id = 9,
                            AvailableAt = "Alcudia",
                            DailyRate = 100.00m,
                            Description = "Five-door compact sedan (segment C) equipped with a fully electric drive (can travel approximately 350 km on a single charge), produced since 2017. The model year is 2017, with a 320HP 222kW P60 engine.",
                            Name = "Model 3"
                        },
                        new
                        {
                            Id = 10,
                            AvailableAt = "Alcudia",
                            DailyRate = 1200.00m,
                            Description = "Luxury model in the E segment, powered by an electric motor with 1020HP, 750kW of power, capable of traveling approximately 637km on a single charge. Model year 2021. It has 5 doors.",
                            Name = "Model S"
                        },
                        new
                        {
                            Id = 11,
                            AvailableAt = "Alcudia",
                            DailyRate = 240.00m,
                            Description = "Built on the Model S platform, the Model X was designed to combine the best features of an SUV and a minivan while maintaining sporty performance. The main feature of the Model X is the upward-lifting rear pair of doors - Falcon Wing Doors. The car is from the 2017 model year, with a 503HP 370kW P100D engine.",
                            Name = "Model X"
                        },
                        new
                        {
                            Id = 12,
                            AvailableAt = "Alcudia",
                            DailyRate = 190.00m,
                            Description = "It features a range of up to 507 kilometers on a single charge and all-wheel drive (AWD) with a dual-motor setup. The vehicle accelerates from 0 to 100 km/h in 5 seconds, and its maximum speed is 217 km/h. It's a comfortable 5-door car with a 450HP engine.",
                            Name = "Model Y"
                        },
                        new
                        {
                            Id = 13,
                            AvailableAt = "Manacor",
                            DailyRate = 100.00m,
                            Description = "Five-door compact sedan (segment C) equipped with a fully electric drive (can travel approximately 350 km on a single charge), produced since 2017. The model year is 2017, with a 320HP 222kW P60 engine.",
                            Name = "Model 3"
                        },
                        new
                        {
                            Id = 14,
                            AvailableAt = "Manacor",
                            DailyRate = 1200.00m,
                            Description = "Luxury model in the E segment, powered by an electric motor with 1020HP, 750kW of power, capable of traveling approximately 637km on a single charge. Model year 2021. It has 5 doors.",
                            Name = "Model S"
                        },
                        new
                        {
                            Id = 15,
                            AvailableAt = "Manacor",
                            DailyRate = 240.00m,
                            Description = "Built on the Model S platform, the Model X was designed to combine the best features of an SUV and a minivan while maintaining sporty performance. The main feature of the Model X is the upward-lifting rear pair of doors - Falcon Wing Doors. The car is from the 2017 model year, with a 503HP 370kW P100D engine.",
                            Name = "Model X"
                        },
                        new
                        {
                            Id = 16,
                            AvailableAt = "Manacor",
                            DailyRate = 190.00m,
                            Description = "It features a range of up to 507 kilometers on a single charge and all-wheel drive (AWD) with a dual-motor setup. The vehicle accelerates from 0 to 100 km/h in 5 seconds, and its maximum speed is 217 km/h. It's a comfortable 5-door car with a 450HP engine.",
                            Name = "Model Y"
                        });
                });

            modelBuilder.Entity("TeslaRenting.Data.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserAddressId")
                        .HasColumnType("int");

                    b.Property<int>("UserRoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserAddressId");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1999, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oskar@test.com",
                            FirstName = "Oskar",
                            LastName = "Michalski",
                            PasswordHash = "$2b$10$n54P7PVEM/AELQkOL/xDxuvKPIFmtIFGVOP4W9A8n9TMPCyuxnuHS",
                            Phone = "123123123",
                            UserAddressId = 1,
                            UserRoleId = 3
                        });
                });

            modelBuilder.Entity("TeslaRenting.Data.Entity.Reservation", b =>
                {
                    b.HasOne("TeslaRenting.Data.Entity.TeslaCar", "TeslaCar")
                        .WithMany("Reservations")
                        .HasForeignKey("TeslaCarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeslaRenting.Data.Entity.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TeslaCar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeslaRenting.Data.Entity.User", b =>
                {
                    b.HasOne("TeslaRenting.Data.Entity.Address", "UserAddress")
                        .WithMany("Users")
                        .HasForeignKey("UserAddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeslaRenting.Data.Entity.Role", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserAddress");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("TeslaRenting.Data.Entity.Address", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TeslaRenting.Data.Entity.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("TeslaRenting.Data.Entity.TeslaCar", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("TeslaRenting.Data.Entity.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
